CREATE VIEW V_TTHOADON
AS
	SELECT HOADON.SOHD, MAKH, SANPHAM.MASP, TENSP, DONGIA, SL, DONGIA*SL AS THANHTIEN
	FROM SANPHAM,HOADON,CTHD
	WHERE SANPHAM.MASP = CTHD.MASP
	AND HOADON.SOHD = CTHD.SOHD

SELECT * FROM V_TTHOADON

INSERT INTO CTHD
VALUES('HD01','SP01',5)
INSERT INTO CTHD
VALUES('HD01','SP02',10)
INSERT INTO CTHD
VALUES('HD02','SP01',5)


-----------------------------------------------
CREATE TRIGGER TR_THEMTRONGVIEWS
ON V_TTHOADON INSTEAD OF INSERT
AS
BEGIN
	--Neu sohd da co thi update thanhtien thoi ne
	if(EXISTS (SELECT SOHD FROM INSERTED WHERE SOHD IN(SELECT SOHD FROM HOADON)))
	BEGIN
		UPDATE HOADON
		SET THANHTIEN = THANHTIEN + (SELECT SL*DONGIA FROM inserted)
		WHERE SOHD = (SELECT SOHD FROM inserted)
	END

	ELSE
	BEGIN
		INSERT INTO HOADON
		SELECT SOHD, MAKH,THANHTIEN FROM inserted
	END

	--Neu masp ko co trong SANPHAM thi se duoc them vao
	IF(NOT EXISTS(SELECT MASP FROM inserted WHERE MASP IN(SELECT MASP FROM SANPHAM)))
	BEGIN
		INSERT INTO SANPHAM
		SELECT MASP, TENSP, DONGIA FROM inserted
	END

	--them vao CTHD
	INSERT INTO CTHD
	SELECT SOHD,MASP,SL FROM inserted
END

INSERT INTO V_TTHOADON
VALUES('HD03','KH01','SP01','KH01')
INSERT INTO V_TTHOADON
VALUES('HD01','SP02',10,'KH01')
INSERT INTO V_TTHOADON
VALUES('HD02','SP01',5,'KH02')
