CREATE VIEW ABC
AS
SELECT HOADON.SOHD,MAKH,SANPHAM.MASP,GIA,SL,GIA*SL AS THANHTIEN
FROM HOADON,CTHD,SANPHAM
WHERE HOADON.SOHD = CTHD.SOHD
AND SANPHAM.MASP = CTHD.MASP

SELECT * FROM ABC

CREATE TRIGGER THEM_VIEW
ON ABC INSTEAD OF INSERT
AS
BEGIN
	IF EXISTS (SELECT SOHD FROM inserted)
	BEGIN TRAN THEM
	BEGIN
		IF(EXISTS(SELECT SOHD FROM inserted WHERE SOHD NOT IN(SELECT SOHD FROM HOADON)))
		BEGIN
			ROLLBACK TRAN THEM
		END
		IF(EXISTS(SELECT MAKH FROM inserted WHERE MAKH NOT IN(SELECT MAKH FROM KHACHHANG)))
		BEGIN
			ROLLBACK TRAN THEM
		END
		IF(EXISTS(SELECT MASP FROM inserted WHERE MASP NOT IN(SELECT MASP FROM SANPHAM)))
		BEGIN
			ROLLBACK TRAN THEM
		END
	END

	IF @@ERROR = 1
	BEGIN
		ROLLBACK TRAN THEM
	END

	ELSE
	BEGIN
		INSERT INTO CTHD
		SELECT SOHD,MASP,SL FROM inserted
		COMMIT TRAN THEM
		PRINT'DA THEM VAO CTHD'
	END
END

INSERT INTO ABC(SOHD,MAKH,MASP,SL)
VALUES('1001','KH01','BB04',100)


CREATE TRIGGER XOA_VIEW
ON ABC INSTEAD OF DELETE
AS
BEGIN
	IF(EXISTS(SELECT SOHD FROM deleted))
	BEGIN
		DELETE FROM CTHD
		WHERE SOHD = (SELECT SOHD FROM deleted)
		AND MASP = (SELECT MASP FROM deleted)
		PRINT 'DA XOA VAO BANG CTHD'
	END
END

DELETE FROM ABC
WHERE SOHD = '1001'
AND MAKH = 'KH01'
AND MASP = 'BB04'

CREATE TRIGGER CAPNHAT_VIEW
ON ABC INSTEAD OF UPDATE
AS
BEGIN
	IF(EXISTS(SELECT SOHD FROM inserted))
	BEGIN
		UPDATE CTHD
		SET SL = (SELECT SL FROM inserted)
		WHERE SOHD = (SELECT SOHD FROM inserted)
		AND MASP = (SELECT MASP FROM inserted)
		PRINT 'DA CAP NHAT VAO BANG CTHD'
	END
END

UPDATE ABC
SET SL = 1000
WHERE SOHD = '1001'
AND MAKH = 'KH01'
AND MASP = 'BB03'